name: new Basic workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
    push:
        branches: ['main']

jobs:
    first:
        name: "first-test-job"
        runs-on:
            - ubuntu-linux
        
        steps:
            - name: Send greeting
            run: |
                echo "Hello ${{github.name}}" 



